# Generated by Django 4.2.5 on 2023-09-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='lastname_2',
        ),
    ]
