# Generated by Django 4.2.5 on 2023-09-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_lastname_member_lastname_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname_2',
            new_name='lastname',
        ),
    ]
